runtime: java
env: flex
runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "21"
resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10
env_variables:
  SPRING_PROFILES_ACTIVE: prod
handlers:
- url: /.*
  script: auto
  secure: always
